#!/bin/sh

cd `dirname $0`

CELESTIA_ANDROID_ROOT=$1
CELESTIA_LOCALIZATION_REPO_ROOT=`pwd`/../../CelestiaLocalization
CELESTIA_LOCALIZATION_ANDROID_ROOT=$CELESTIA_LOCALIZATION_REPO_ROOT/android

rsync -rv --quiet $CELESTIA_LOCALIZATION_ANDROID_ROOT/* $CELESTIA_ANDROID_ROOT
