jobs:
- job: Build
  displayName: 'Build'
  pool:
    vmImage: 'ubuntu-latest'

  variables:
    outputFormat: ${{ parameters.outputFormat }}
    appCenterSecret: ${{ parameters.appCenterSecret }}
    appCenterToken: ${{ parameters.appCenterToken }}
    appCenterProject: ${{ parameters.appCenterProject }}
    contentCommitHash: ${{ '6b9417781a6beb0ded8a1116c60c93c478830a2e' }}

  steps:
  - checkout: Celestia
    fetchDepth: 0
  - checkout: CelestiaContent
    fetchDepth: 0
  - checkout: CelestiaLocalization
    fetchDepth: 0
  - checkout: self
    fetchDepth: 0

  - script: |
      sudo apt update
      sudo apt install -y gettext gperf
    displayName: 'Install Dependencies'

  - script: |
      npm install -g appcenter-cli
    displayName: 'Install AppCenter-CLI'

  - script: |
      cd Celestia
      git checkout origin/$(Build.SourceBranchName)
      cd ../CelestiaLocalization
      git checkout origin/$(Build.SourceBranchName)
    displayName: 'Checkout Branch'
    condition: ne( variables['Build.Reason'], 'PullRequest' )

  - script: |
      cd Celestia
      git checkout origin/$(System.PullRequest.TargetBranch)
      cd ../CelestiaLocalization
      git checkout origin/$(System.PullRequest.TargetBranch)
    displayName: 'Checkout Branch (PR)'
    condition: eq( variables['Build.Reason'], 'PullRequest' )

  - script: |
      cd CelestiaContent
      git checkout $(contentCommitHash)
    displayName: 'Checkout Content'

  - script: |
      sh $(System.DefaultWorkingDirectory)/AndroidCelestia/app/run_gperf.sh $(System.DefaultWorkingDirectory)/Celestia
    displayName: 'Running gperf'

  - script: |
      mkdir -p AndroidCelestia/dependencies
    displayName: 'Creating Directories for Third Party Dependencies'

  - task: UniversalPackages@0
    inputs:
      command: 'download'
      downloadDirectory: 'AndroidCelestia/dependencies'
      feedsToUse: 'internal'
      vstsFeed: '9f9dcde1-dcba-4537-8214-71c8a03b99a0/14bb1031-e6b2-40ac-b287-73e7fcb5900e'
      vstsFeedPackage: '8024e780-0af6-4980-8246-df6550e8d1b6'
      vstsPackageVersion: '0.0.15'
    displayName: 'Download Dependencies'

  - script: |
      sed -i 's/APPCENTER-APP-ID/$(appCenterSecret)/g' app/src/play/java/space/celestia/mobilecelestia/Flavor.kt
      echo "New Content:"
      cat app/src/play/java/space/celestia/mobilecelestia/Flavor.kt
    workingDirectory: '$(System.DefaultWorkingDirectory)/AndroidCelestia'
    displayName: 'Replace AppCenter Placeholders'

  - task: JavaToolInstaller@0
    inputs:
      versionSpec: '17'
      jdkArchitectureOption: 'x64'
      jdkSourceOption: 'PreInstalled'
    displayName: 'Install Java 17'

  - task: Gradle@2
    inputs:
      workingDirectory: '$(system.defaultWorkingDirectory)/AndroidCelestia'
      gradleWrapperFile: '$(system.defaultWorkingDirectory)/AndroidCelestia/gradlew'
      gradleOptions: '-Xmx3072m'
      publishJUnitResults: false
      testResultsFiles: '**/TEST-*.xml'
      tasks: 'assembleSideloadRelease'
    displayName: 'Build APK'
    condition: eq( variables['outputFormat'], 'apk' )

  - task: Gradle@2
    inputs:
      workingDirectory: '$(system.defaultWorkingDirectory)/AndroidCelestia'
      gradleWrapperFile: '$(system.defaultWorkingDirectory)/AndroidCelestia/gradlew'
      gradleOptions: '-Xmx3072m'
      publishJUnitResults: false
      testResultsFiles: '**/TEST-*.xml'
      tasks: 'bundlePlayRelease'
    displayName: 'Build AAB'
    condition: eq( variables['outputFormat'], 'aab' )

  - task: AndroidSigning@3
    inputs:
      apkFiles: '$(system.defaultWorkingDirectory)/**/*.apk'
      apksign: true
      apksignerKeystoreFile: 'celestia.jks'
      apksignerKeystorePassword: '$(JARSIGNER_KEYSTORE_PASSWORD)'
      apksignerKeystoreAlias: 'celestia'
      apksignerKeyPassword: '$(JARSIGNER_KEY_PASSWORD)'
      zipalign: true
    displayName: 'Sign APK'
    condition: eq( variables['outputFormat'], 'apk' )

  - task: DownloadSecureFile@1
    name: keyStoreFile
    displayName: 'Download KeyStore File'
    inputs:
      secureFile: 'celestia.jks'
    condition: eq( variables['outputFormat'], 'aab' )

  - script: |
      jarsigner -verbose -sigalg SHA256withRSA -digestalg SHA-256 -keystore $(keyStoreFile.secureFilePath) -storepass $(JARSIGNER_KEYSTORE_PASSWORD) -keypass $(JARSIGNER_KEY_PASSWORD) $(system.defaultworkingdirectory)/AndroidCelestia/app/build/outputs/bundle/playRelease/*.aab celestia
    displayName: "Sign AAB"
    condition: eq( variables['outputFormat'], 'aab' )

  - script: |
      rm -rf $(system.defaultworkingdirectory)/AndroidCelestia/app/build/intermediates/intermediary_bundle/*
    displayName: 'Remove Redundant AAB'
    condition: eq( variables['outputFormat'], 'aab' )

  - task: CopyFiles@2
    inputs:
      sourceFolder: '$(system.defaultWorkingDirectory)'
      contents: '**/*.$(outputFormat)'
      targetFolder: '$(build.artifactStagingDirectory)'
      flattenFolders: true
    displayName: 'Copy APK/AAB'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: '$(outputFormat)'
      publishLocation: 'Container'
    displayName: 'Publish Build Artifacts'

  - script: |
      mkdir -p symbols
      cp -r $(system.defaultWorkingDirectory)/AndroidCelestia/app/build/intermediates/cxx/RelWithDebInfo/**/obj/* symbols
      cp -r $(system.defaultWorkingDirectory)/AndroidCelestia/Celestia/build/intermediates/cxx/RelWithDebInfo/**/obj/* symbols
      cp -r $(system.defaultWorkingDirectory)/AndroidCelestia/app/build/intermediates/native_symbol_tables/release/out/* symbols
      cd symbols
      zip -vr symbols.zip * -x "*.DS_Store"
      appcenter crashes upload-symbols --breakpad symbols.zip --app $(appCenterProject) --token $(appCenterToken) --disable-telemetry --debug
    displayName: 'Upload Symbols'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'symbols/symbols.zip'
      ArtifactName: '$(outputFormat)-symbols'
      publishLocation: 'Container'
    displayName: 'Publish Symbols'

  - script: |
      export VERSION_CODE=`grep versionCode $(system.defaultWorkingDirectory)/AndroidCelestia/app/src/main/AndroidManifest.xml | cut -d\" -f2`
      export VERSION_NAME=`grep versionName $(system.defaultWorkingDirectory)/AndroidCelestia/app/src/main/AndroidManifest.xml | cut -d\" -f2`
      mkdir -p mapping
      cp -r $(system.defaultWorkingDirectory)/AndroidCelestia/app/build/outputs/mapping/**/mapping.txt mapping
      appcenter crashes upload-mappings --mapping mapping/mapping.txt --version-name $VERSION_NAME --version-code $VERSION_CODE --app $(appCenterProject) --token $(appCenterToken) --disable-telemetry --debug
    displayName: 'Upload Mapping'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'mapping/mapping.txt'
      ArtifactName: '$(outputFormat)-mapping'
      publishLocation: 'Container'
    displayName: 'Publish Mapping'
